version: 1
disable_existing_loggers: False

formatters:
  detail:
    format: '%(asctime)s %(levelname)s [%(processName)s] %(name)s.%(funcName)s: %(message)s (%(filename)s:%(lineno)s)'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detail
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detail
    filename: afinn-service.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: INFO
  handlers: [console, file_handler]